import java.util.Scanner;

/*
Nabil Sharif
Introduction to Computer Science
Chapter 2 - Chapter2Project5.java
Description: 
Write a program that displays the pattern in the textbook.
*/

public class SalesPrediction {

    public static void main(String[] args) {
    	
    	double totalSales, totalGeneratedByECD,
    	percentOfTotalSales = 0.62;
    	
    	//Create a scanner object in memory
    	Scanner keyboard = new Scanner(System.in);
    	
    	//Ask user for total sales and stores it in totalSales
    	System.out.print("Enter your total sales:"
    			+ "(i.e. $4.6 million is 4600000): ");
    	totalSales = keyboard.nextDouble();
    	
    	//Compute the total generated by East Coast Sales
    	totalGeneratedByECD = 
    			(totalSales * percentOfTotalSales);
    	
    	//Display the East Coast Sales division's totalSales,* 
    	//**totalGeneratedByECD, and percentOfTotalSales.
    	System.out.print("The East Coast sales division" +
    			" generated 62% of the $" + totalSales + 
    			"\nin total Sales, which means that the ECD " 
    			+ "generated $" + totalGeneratedByECD + "."); 
    	
    	keyboard.close();
    }
}

